import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NextAuthProvider } from "./components/Providers";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Realtime Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Navbar />
          <main className="mt-24">{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
